import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['uz', 'ru', 'en', 'kk', 'ky', 'tr', 'ar'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? uzText = '',
    String? ruText = '',
    String? enText = '',
    String? kkText = '',
    String? kyText = '',
    String? trText = '',
    String? arText = '',
  }) =>
      [uzText, ruText, enText, kkText, kyText, trText, arText][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'nq5o8u2h': {
      'uz': 'Restoran xodimlari paneli',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '3h4k5pks': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'qph5p7k3': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'u7cpe4w3': {
      'uz': 'Login',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'dmia795j': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'cw36kjgx': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'hgpq2all': {
      'uz': 'Parol',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '89ymr2dx': {
      'uz': 'KIRISH',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6va45app': {
      'uz': 'Direktor paneliga kirishni tasdiqlang',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'q0ae4bxh': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // DirectorPage
  {
    'x9ocbgjm': {
      'uz': 'Oylik to\'lov: 30 kun',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'qm7wav9y': {
      'uz': 'R Kepper ulanish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ojn1p6dx': {
      'uz': 'Yandex ulanish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wtxoqihy': {
      'uz': 'Admin nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'l6z8zlzz': {
      'uz': 'Chef povar nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '1n5mtkui': {
      'uz': 'Ofitsant nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'xun4w7s5': {
      'uz': 'Ofitsant foizi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ubdfl5sx': {
      'uz': 'Yangi ofitsant qo\'shish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wmc2rj0j': {
      'uz': 'Kuryerlar nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'rgdu5t2f': {
      'uz': 'Z-hisobot',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'vkt28ut6': {
      'uz': 'MenyuBoshqaruv',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'w8iewc0j': {
      'uz': 'Otzivlarni ko\'rish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wa3vt4sl': {
      'uz': 'Login va parolni o\'zgartirish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'f2zvjyi5': {
      'uz': '📢 Push-xabarlar va Aksiyalar',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'sjrnmrt3': {
      'uz': 'Texnik yordam ( chat )',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4bv9z1ml': {
      'uz': 'Sertificate',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'xaaavzl4': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // AdminPage
  {
    'cwrzjrad': {
      'uz': 'R Kepper ulanish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '2sm5r8lf': {
      'uz': 'Yandex ulanish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'vaxiksjc': {
      'uz': 'Chef povar nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'x0o7mjgy': {
      'uz': 'Ofitsant nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'qrzdh5na': {
      'uz': 'Kuryerlar nazorati',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ncivjiz6': {
      'uz': 'Ofitsant foizi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ljf07kx0': {
      'uz': 'Yangi ofitsant qo\'shish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ff2hp2gw': {
      'uz': 'Z-hisobot',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'k00u468d': {
      'uz': 'Otzivlarni ko\'rish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '188nosgj': {
      'uz': 'Sertificate',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'prhjcq09': {
      'uz': 'Texnik yordam ( chat )',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '3ut7rdmv': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // ChefPage
  {
    'kisx35st': {
      'uz': 'Zaldagi buyurtmalar',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'gusldto5': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'fb589p1p': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'uqsvbz6q': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'zxjsm26f': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ss041z5w': {
      'uz': 'STOL №2  |  Ofitsiant: Sardor',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '2qmt9wvk': {
      'uz': '2x Lag\'mon',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ea8dazmu': {
      'uz': '⚠️ Eslatma: Achchiq bo\'lsin',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'nzwio0ul': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '467z3ert': {
      'uz': 'STOL №8  |  Ofitsiant: Madina',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '8zihzetk': {
      'uz': '1x Shashlik (Qo\'y)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '7xqc7vqw': {
      'uz': '⚠️ Eslatma: Shoshilinch, tezroq bo\'lsin',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'jb3y3urz': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'bmb963pt': {
      'uz': 'Yandex buyetmalar',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '193u12ui': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'm60wzlez': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'rd2yvrbc': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '01kik6x3': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '280hgcag': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6fcw1mug': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '5prq66y1': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yxuby2c3': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tbazn5c6': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '0xt2giib': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '1gnzg4mn': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    't5et7mlt': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '64widzkf': {
      'uz': 'Dostavka',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '7ocwd7la': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ow83cqo0': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ujrandhn': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wgufdpxy': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'djcgb1p2': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '1dpopijv': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '84sgwo2d': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'dhmiqjb2': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tmih7ke0': {
      'uz': 'STOL №5  |  Ofitsiant: Ahror',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '5uo0rs55': {
      'uz': '1x Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'aw7lk3u6': {
      'uz': '⚠️ Eslatma: Piyozsiz bo\'lsin, yog\'i kamroq',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '0k9k051c': {
      'uz': 'TAYYOR',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ja6ff3hu': {
      'uz': '📋 Menyuni boshqarish (Stop-List)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yci4qt4m': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // OfitsiantPage
  {
    'cf043oig': {
      'uz': '➕ Yangi buyurtma (Stol ochish)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '5rtc4sn1': {
      'uz': '📌 Yopilmagan stollar ro\'yxati:',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'owuv0huf': {
      'uz': '🔴 STOL №9',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    've6eb6y0': {
      'uz': 'Buyurtma summasi: 180 000 UZS',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'oumlpf5j': {
      'uz': '🔴 STOL №4',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ui35gnma': {
      'uz': 'Buyurtma summasi: 450 000 UZS',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ry86c3nn': {
      'uz': '💰 Bugungi foizingiz: 0 UZS',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '52di37s3': {
      'uz': 'Yandex coy puli',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '0h0k49k2': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // StopListPage
  {
    '5vrh1jgy': {
      'uz': '📋 Taomlar stop-listi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '88k512up': {
      'uz': '1. Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tyy6e0mo': {
      'uz': 'START',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tvekwmgc': {
      'uz': 'STOP',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '10bjm79x': {
      'uz': '2. Lag\'mon (Uyg\'urcha)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'k64lccjb': {
      'uz': 'START',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'v64ybc3r': {
      'uz': 'STOP',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '86xqxua1': {
      'uz': '3. Shashlik (Qo\'y go\'shti)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '84d88urs': {
      'uz': 'START',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '7u35jptz': {
      'uz': 'STOP',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6x5ircow': {
      'uz': '4. Pitsa (Assorti)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'pvwd1g63': {
      'uz': 'START',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wrsuxoqm': {
      'uz': 'STOP',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'zlijewps': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // MenyuBoshqaruvPage
  {
    'javti6kt': {
      'uz': '👑 Menyuni tahrirlash (Narx va Rasm)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    's9owfv6x': {
      'uz': '1. Osh (Milliy)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'cdyigmxy': {
      'uz': 'Narxi (UZS)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4p6kb18u': {
      'uz': 'OK',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ko774yc1': {
      'uz': '2. Lag\'mon',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4grbhln9': {
      'uz': 'Narxi (UZS)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'j17zg0ty': {
      'uz': 'OK',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '3urw2oey': {
      'uz': '3. Shashlik',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'o3vyd980': {
      'uz': 'Narxi (UZS)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'gdbwzijw': {
      'uz': 'OK',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'iumd7dav': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // PushVaAksiyaPage
  {
    'n0p4cs49': {
      'uz': '📢 Push-xabarlar va Aksiyalar',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    's18knirg': {
      'uz': 'Xodimlarga yuboriladigan xabar matnini kiriting...',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '8vpyxwqu': {
      'uz': '🚀 PUSH-XABARNI YUBORISH (XODIMLARGA)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '542yn50i': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // DostavchikPage
  {
    'pka9yrms': {
      'uz': '🚴 Kuryer (Dostavka) paneli',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4szs1rf7': {
      'uz': 'Buyurtma №1450',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '57l7dpd4': {
      'uz': '📍 Manzil: Moskva, tinchlik ko\'chasi 45-uy',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'mt3slfij': {
      'uz': '📞 Tel: +7 (999) 123-45-67',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'lfexzkgu': {
      'uz': '💵 To\'lov: Sberbank (Karta) yoki Naqd',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '98fkuzy8': {
      'uz': '✅ YETKAZIB BERILDI (OK)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6okth50p': {
      'uz': 'Buyurtmalar tarihi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'cwcoz6sp': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // AddWaiterComponent
  {
    'klrbiy9o': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'g6nrv7d4': {
      'uz': 'Ofitsiant ismi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '39qxtehp': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'v152x62e': {
      'uz': 'Login',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'lf7ei4lc': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'q93fiy0x': {
      'uz': 'Parol',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'lnh9xzrw': {
      'uz': 'Ofitsiantni saqlash',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'eo7807vj': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // ChangePasswordPage
  {
    'y6ji2xpx': {
      'uz': 'Yangi login',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'upb3em63': {
      'uz': 'Yangi parol',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'y6rh0sy8': {
      'uz': 'O\'zgarishlarni saqlash',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6p33nb4a': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // OfitsiantFoizPage
  {
    'zmmz6beb': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // OtzivlarniKorishPage
  {
    'sfnwtog5': {
      'uz': 'Mijozlar Fikr va Reytinglari 💬',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '2izor703': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // RKeeperPage
  {
    '6ih6763s': {
      'uz': 'r-keeper Kassa Integratsiyasi ⚙️',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'o3n9233y': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'kq23hglm': {
      'uz': 'r-keeper API URL',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4c6cw93r': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ursnz1ov': {
      'uz': 'Kassa Foydalanuvchi Nomi (Login)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'o1bz4f89': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wjla717r': {
      'uz': 'Kassa Maxfiy Token / Parol',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'htwgow50': {
      'uz': 'r-keeper Tizimiga Ulanish ⚡️',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'h5fttgmj': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // YandexPage
  {
    'xkyoei1q': {
      'uz': 'Yandex Eats Integratsiyasi 🚗',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'az12lvbn': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'lt6d2k9x': {
      'uz': 'Yandex Merchant ID (Маъмур коди)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yfnxpp9z': {
      'uz': 'TextField',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'k6vkhx0r': {
      'uz': 'Yandex Delivery API Token / Пароль',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tu9gqunr': {
      'uz': 'Yandex Eats Хизматини Ёқиш ⚡️',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yb3xzmpo': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // KiberAuthShield
  {
    'raf7grgg': {
      'uz': 'Ikki bosqichli SMS-kod 🔑',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'kajh384x': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // OfitsiantChoyPuliPage
  {
    '78mvxwr3': {
      'uz': 'Joriy balansingiz:',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '0rtjtz4b': {
      'uz': 'Mijozlarga ko\'rsatish uchun shaxsiy QR-kod',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'odb9gpsx': {
      'uz': 'Pulni kartaga yechib olish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '32l1zk5k': {
      'uz': 'Mening choy pullarim',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '50bmk0fb': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // AccountPage
  {
    'p3nurulo': {
      'uz': 'Ism va familiyangizni kiriting',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'z6jysrrr': {
      'uz': 'Elektron pochtangizni kiriting (@mail)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '71ad8dz9': {
      'uz': 'Jinsingizni tanlang',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yducfqcs': {
      'uz': 'Search...',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'fvvjcvxr': {
      'uz': 'Erkak',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'p0mh2lad': {
      'uz': 'Ayol',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ut8lmklx': {
      'uz': 'Option 3',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'z3f0c1fi': {
      'uz': 'Tug\'ilgan sanani tanlash',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'hejb1tr6': {
      'uz': 'Biometrik xavfsizlik (FaceID / TouchID)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '5j1444q5': {
      'uz': 'Ilovaga kirishda yuz va barmoq izini talab qilish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yrfwsmsg': {
      'uz': 'PROFILNI TASDIQLASH',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'dga89mkq': {
      'uz': 'AKKAUNTNI BUTUNLAY O\'CHIRISH',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'op2jqz7h': {
      'uz': 'Shaxsiy ma\'lumotlar',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'yh9833a0': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // DostavkaTarixiPage
  {
    '82ic6mgv': {
      'uz': 'Buyurtmalar tarixi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tdge5hm0': {
      'uz': 'Buyurtma №1450',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tiw9dx9y': {
      'uz': '📍 Manzil: Moskva, tinchlik ko\'chasi 45-uy',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'cdybil8t': {
      'uz': '📞 Tel: +7 (999) 123-45-67',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'cfu7seqz': {
      'uz': '💵 To\'lov: Sberbank (Karta) yoki Naqd',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'krbp8y64': {
      'uz': '✅ YETKAZIB BERILDI (OK)',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'ejq54n3u': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // ClientCartPage
  {
    '63eh1adn': {
      'uz': 'Zalda o\'tirish 🍽️',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '9hqwczn0': {
      'uz': 'Dostavka 🚗',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'h2w3vnxw': {
      'uz': 'Sizning Buyurtmalaringiz 🛍️',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'n4sxtwog': {
      'uz': 'To\'y Palovi',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6e552dfc': {
      'uz': '➕ Yana taom qo\'shish',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'i6ghs8ih': {
      'uz': 'Taomlar summasi:',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'gkex3137': {
      'uz': '45 000 so\'m',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'bt1fozyt': {
      'uz': 'Xizmat haqi (10%):',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'jl57jj96': {
      'uz': '4 500 so\'m',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '26q52rat': {
      'uz': 'Jami to\'lov:',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '409gmo4d': {
      'uz': '🚀 BUYURTMANI YUBORISH',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'vp3lhs6d': {
      'uz': '🖨️ PRECHEK CHIQARISH',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4zmwu0dk': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // StolOchishDialog
  {
    'a4eyxhy7': {
      'uz': 'Stol raqami...',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4unxjv4n': {
      'uz': 'Mehmonlar soni...',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'iprapvpg': {
      'uz': 'Menyuga kirish ➡️',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '6my4954t': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // OfitsiantMenyuPage
  {
    'u046mzjl': {
      'uz': '🔍 Taomni qidirish (Ovoz orqali)...',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wvhxel1h': {
      'uz': 'Palov',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'omkphkal': {
      'uz': '1',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'os0b0qgp': {
      'uz': 'Home',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
  // Miscellaneous
  {
    'l2omfp6x': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'vk2sndy8': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'dfk33o10': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'qlee9rpy': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'sjwrot05': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '7ax1u3al': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'iunnk25y': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tqjku9uw': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '0akryilj': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'qppvn58j': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'poa6yrr6': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'gwscp8kq': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '9abrqv8x': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'y1t5viru': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'zmupc763': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '9hzbqmgu': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '9zitxttn': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'um0qyh0x': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'aauozyrv': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'vgdbhknm': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'rtnb3lap': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'tb88uqja': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '9f5y1jwo': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'wyll8z94': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'qf9ng42c': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    '4q7fs07i': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'aov45o1o': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'q1y38wev': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
    'v4wwvxdk': {
      'uz': '',
      'ar': '',
      'en': '',
      'kk': '',
      'ky': '',
      'ru': '',
      'tr': '',
    },
  },
].reduce((a, b) => a..addAll(b));
